---
- name: DHCP szerver konfigurálása role segítségével
  hosts: DHCP
  pre_tasks:
    - name: AppArmor telepítése (mivel a debian lxc-n nincs alapból de a bertvv.dhcp alapnak veszi)
      ansible.builtin.package:
        name: apparmor
        state: latest
  roles:
    - role: bertvv.dhcp

- name: A szuper számítógép konfigurálása mqtt brókernek
  hosts: SC.internal
  tasks:
    - name: EPEL telepítése mivel ebben van a mosquitto
      ansible.builtin.package:
        name: epel-release
        state: latest

    - name: Mosquitto telepítése 
      ansible.builtin.package:
        name: 
          - mosquitto
        state: latest
        enablerepo: epel
        update_cache: yes

    - name: A mosquitto konfihurációs fájljának felmásolása
      ansible.builtin.copy:
        src: "./SCconf/mosquitto.conf"
        dest: "/etc/mosquitto/mosquitto.conf"

    - name: A mosquitto elindítása
      ansible.builtin.systemd:
        name: mosquitto
        state: started
        enabled: yes

    - name: Tűzfal engedélyezés DNS 
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 1883/tcp

- name: DNS szerver konfigurálása role segítségével
  hosts: DNS
  pre_tasks:
    - name: BIND és OpenSSL könyvtárak kényszerített frissítése a függőségi  hiba javításához
      ansible.builtin.dnf:
        name:
          - bind-libs
          - bind-utils
          - openssl-libs
          - openssl
        state: latest
        update_cache: yes
      when: ansible_facts['os_family'] == "RedHat"
      register: repair_result

    - name: DNF gyorsítótár ürítése (ha volt frissítés)
      ansible.builtin.command: dnf clean all
      when: repair_result.changed
  roles:
    - role: brunobenchimol.bind 
  tasks:
    - name: Tűzfal engedélyezés DNS 
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 53/udp
        - 53/tcp


- name: Docker telepítése és HTTPS (Caddy) és VPN konténer indítása 
  hosts: WEB 
  vars:
    docker_compose_dir: "/opt/docker"

  tasks:
    - name: Szükséges segédprogramok telepítése (yum-utils)
      ansible.builtin.package:
        name: yum-utils
        state: present

    - name: iptables_nat betöltés a wireguardnak
      ansible.builtin.copy:
        dest: /etc/modules-load.d/iptable_nat.conf
        content: "iptable_nat\n"
        owner: root
        group: root
        mode: '0644'

    - name: Modul azonnali betoltese (runtime)
      community.general.modprobe:
        name: iptable_nat
        state: present

    - name: Docker tároló hozzáadása
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Docker motor és CLI telepítése
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Docker szolgáltatás elindítása és engedélyezése
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Projekt könyvtár létrehozása a docker-compose számára
      ansible.builtin.file:
        path: "{{ docker_compose_dir }}"
        state: directory
        mode: '0755'

    - name: docker-compose.yml másolása a szerverre
      ansible.builtin.copy:
        src: ./WEBsource/docker-compose.yml
        dest: "{{ docker_compose_dir }}/docker-compose.yml"

    - name: Caddy fájlok másolása
      ansible.builtin.copy:
        src: ./WEBsource/Caddyfile
        dest: "{{ docker_compose_dir }}/Caddyfile"

    - name: a webszerver html másolása
      ansible.builtin.copy:
        src: ./WEBsource/html/
        dest: "{{ docker_compose_dir }}/html/"

    - name: Konténerek indítása Docker Compose-al
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: "{{ docker_compose_dir }}"


- name: NFS Szerver konfigurálása role segítségével
  hosts: FILE
  pre_tasks:
    - name: Megosztandó könyvtár létrehozása
      ansible.builtin.file:
        path: "/var/nfs/shared_data"
        state: directory
        mode: '0777'
        owner: nobody
        group: nobody
  roles:
    - role: geerlingguy.nfs
  tasks:
    - name: Tűzfal engedélyezés NFS
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - nfs
        - rpc-bind
        - mountd
